---
- name: Check if Filebeat is installed
  command: dpkg-query -W filebeat
  register: filebeat_check_deb
  failed_when: filebeat_check_deb.rc > 1
  changed_when: filebeat_check_deb.rc == 1

- name: Download filebeat
  get_url: 
    url="{{ filebeat_url }}"
    dest="/opt/{{ filebeat_pkg_name }}.deb"
  sudo: true
  when: filebeat_check_deb.rc == 1

- name: Install my_package
  apt: deb="/opt/{{ filebeat_pkg_name }}.deb"
  sudo: true
  when: filebeat_check_deb.rc == 1

- name: Copy filebeat.yml
  copy:
    src: "{{ filebeat_yml_src }}"
    dest: "{{ filebeat_yml_dest }}"
    sudo: yes
  notify:
    - restart filebeat
